import { DbFestival } from '@/lib/supabase'

export interface FestivalDef {
  id: string
  name: string
  shortName: string
  startDate: string
  endDate: string
  time: string
  venueName: string
  address: string
  city: string
  ticketUrl: string
  infoUrl: string
  image: string | null
  categories: string[]
  isFree: boolean
  description: string
}

export function fromDb(row: DbFestival): FestivalDef {
  return {
    id: row.id,
    name: row.name,
    shortName: row.short_name,
    startDate: row.start_date,
    endDate: row.end_date,
    time: row.time,
    venueName: row.venue_name,
    address: row.address,
    city: row.city,
    ticketUrl: row.ticket_url,
    infoUrl: row.info_url,
    image: row.image,
    categories: row.categories,
    isFree: row.is_free,
    description: row.description,
  }
}

export const FESTIVALS_STATIC: FestivalDef[] = [
  {
    id: 'hcf-2026',
    name: 'Helsinki City Festival 2026',
    shortName: 'Helsinki City Festival',
    startDate: '2026-06-12',
    endDate: '2026-06-14',
    time: '12:00',
    venueName: 'Nordis / Helsingin Jäähalli',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.helsinkicityfestival.fi/en/',
    infoUrl: 'https://www.helsinkicityfestival.fi/en/',
    image: null,
    categories: ['Musiikki', 'Festivaali'],
    isFree: false,
    description: 'Kansainvälinen musiikkifestivaali Nordis-alueella. 50+ artistia kolmena päivänä.',
  },
  {
    id: 'tuska-2026',
    name: 'Tuska Open Air Metal Festival 2026',
    shortName: 'Tuska',
    startDate: '2026-06-26',
    endDate: '2026-06-28',
    time: '12:00',
    venueName: 'Suvilahti',
    address: 'Koksikatu 4',
    city: 'Helsinki',
    ticketUrl: 'https://tuska.fi/en/tickets/',
    infoUrl: 'https://tuska.fi/en/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Metal'],
    isFree: false,
    description: 'Pohjoismaiden suurin metallifestivaali Suvilahden entisellä voimalaitosalueella.',
  },
  {
    id: 'jytakesa-2026',
    name: 'Jytäkesä Go-Go 2026',
    shortName: 'Jytäkesä Go-Go',
    startDate: '2026-07-31',
    endDate: '2026-08-01',
    time: '12:00',
    venueName: 'Suvilahti',
    address: 'Koksikatu 4',
    city: 'Helsinki',
    ticketUrl: 'https://www.tiketti.fi/jytakesa-go-go-2026-suvilahti-helsinki-lippuja/110812',
    infoUrl: 'https://jytakesagogo.com',
    image: 'https://jytakesagogo.com/wp-content/uploads/2025/11/jytis26_header.jpg',
    categories: ['Musiikki', 'Festivaali', 'Rock'],
    isFree: false,
    description: "Kahden päivän rock- ja indie-musiikkifestivaali Suvilahden kentällä. Esiintyjinä mm. Turbonegro, Risto, Ismo Alanko, Fun Lovin' Criminals.",
  },
  {
    id: 'flow-2026',
    name: 'Flow Festival 2026',
    shortName: 'Flow Festival',
    startDate: '2026-08-14',
    endDate: '2026-08-16',
    time: '12:00',
    venueName: 'Suvilahti',
    address: 'Koksikatu 4',
    city: 'Helsinki',
    ticketUrl: 'https://www.flowfestival.com/en/tickets/',
    infoUrl: 'https://www.flowfestival.com/en/',
    image: null,
    categories: ['Musiikki', 'Festivaali'],
    isFree: false,
    description: 'Premium musiikki- ja taidefestivaali Suvilahden teollisuusalueella. 90 000 kävijää kolmena päivänä.',
  },
  {
    id: 'juhlaviikot-2026',
    name: 'Helsingin juhlaviikot 2026',
    shortName: 'Juhlaviikot',
    startDate: '2026-08-18',
    endDate: '2026-09-05',
    time: '10:00',
    venueName: 'Useita paikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://helsinkifestival.fi/en/',
    infoUrl: 'https://helsinkifestival.fi/en/',
    image: null,
    categories: ['Kulttuuri', 'Festivaali', 'Taide', 'Musiikki'],
    isFree: false,
    description: 'Helsingin suurin kulttuurifestivaali — konsertit, teatteri, tanssi ja taide ympäri kaupunkia.',
  },
  {
    id: 'taiteidentyo-2026',
    name: 'Taiteiden yö 2026',
    shortName: 'Taiteiden yö',
    startDate: '2026-08-20',
    endDate: '2026-08-20',
    time: '18:00',
    venueName: 'Koko Helsinki',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://helsinkifestival.fi/taiteidenyo/en/',
    infoUrl: 'https://helsinkifestival.fi/taiteidenyo/en/',
    image: null,
    categories: ['Kulttuuri', 'Taide', 'Ilmainen'],
    isFree: true,
    description: 'Yöllinen taidetapahtuma — museot, galleriat, teatterit ja kaupunkitila avautuvat ilmaiseksi yöhön asti.',
  },
  {
    id: 'suuretoluet-2026',
    name: 'Suuret Oluet – Pienet Panimot Helsinki 2026',
    shortName: 'Suuret Oluet Helsinki',
    startDate: '2026-07-12',
    endDate: '2026-07-27',
    time: '12:00',
    venueName: 'Rautatientori',
    address: 'Rautatientori',
    city: 'Helsinki',
    ticketUrl: 'https://www.tiketti.fi/',
    infoUrl: 'https://suuretoluet.fi/helsinki/',
    image: null,
    categories: ['Olut', 'Ruoka & juoma', 'Festivaali', 'Ulkoilma'],
    isFree: false,
    description: 'Suomen suurin craft beer -tapahtuma Rautatientorilla. 50+ pientä panimoa, 200+ olutta.',
  },
  {
    id: 'kallioblockparty-2026',
    name: 'Kallio Block Party 2026',
    shortName: 'Kallio Block Party',
    startDate: '2026-08-01',
    endDate: '2026-08-01',
    time: '12:00',
    venueName: 'Kallio, Helsinki',
    address: 'Fleminginkatu / Helsinginkatu',
    city: 'Helsinki',
    ticketUrl: 'https://www.kallioblockparty.org/',
    infoUrl: 'https://www.kallioblockparty.org/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Ilmainen', 'Ulkoilma'],
    isFree: true,
    description: 'Kallion vuotuinen ilmainen katufestivaali — live-musiikkia, ruokaa ja yhteisöllisyyttä koko päivä.',
  },
  {
    id: 'wejazz-2026',
    name: 'We Jazz Festival 2026',
    shortName: 'We Jazz',
    startDate: '2026-11-19',
    endDate: '2026-11-22',
    time: '18:00',
    venueName: 'Useita paikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://wejazz.fi/',
    infoUrl: 'https://wejazz.fi/',
    image: null,
    categories: ['Jazz', 'Musiikki', 'Festivaali'],
    isFree: false,
    description: 'Helsingin kansainvälinen jazzfestivaali — esiintymispaikkoja ympäri kaupunkia.',
  },
  {
    id: 'slush-2026',
    name: 'Slush 2026',
    shortName: 'Slush',
    startDate: '2026-11-18',
    endDate: '2026-11-19',
    time: '09:00',
    venueName: 'Messukeskus',
    address: 'Messuaukio 1',
    city: 'Helsinki',
    ticketUrl: 'https://slush.org/',
    infoUrl: 'https://slush.org/',
    image: null,
    categories: ['Teknologia', 'Startup', 'Verkostoituminen'],
    isFree: false,
    description: 'Maailman johtava startup- ja teknologiatapahtuma. 13 000+ kävijää Messukeskuksessa.',
  },
  {
    id: 'pride-2026',
    name: 'Helsinki Pride 2026',
    shortName: 'Helsinki Pride',
    startDate: '2026-06-27',
    endDate: '2026-07-04',
    time: '10:00',
    venueName: 'Esplanadi / Kauppatori',
    address: 'Esplanadi',
    city: 'Helsinki',
    ticketUrl: 'https://www.helsinkipride.fi/',
    infoUrl: 'https://www.helsinkipride.fi/',
    image: null,
    categories: ['Pride', 'Kulttuuri', 'Festivaali', 'Ilmainen'],
    isFree: true,
    description: 'Suomen suurin Pride-viikko — paraati, tapahtumat ja juhla LGBTQ+-yhteisölle ja kaikille.',
  },
  {
    id: 'tasteofhelsinki-2026',
    name: 'Taste of Helsinki 2026',
    shortName: 'Taste of Helsinki',
    startDate: '2026-06-04',
    endDate: '2026-06-07',
    time: '12:00',
    venueName: 'Kansalaistori',
    address: 'Kansalaistori 1',
    city: 'Helsinki',
    ticketUrl: 'https://www.tasteofhelsinki.fi/',
    infoUrl: 'https://www.tasteofhelsinki.fi/',
    image: null,
    categories: ['Ruoka & juoma', 'Festivaali', 'Ravintola'],
    isFree: false,
    description: 'Helsingin parhaiden ravintoloiden pop-up festivaali Kansalaistorilla — huippukeittiöt, ruokamestariat ja juomatarjoilu.',
  },
  {
    id: 'marathon-2026',
    name: 'Björn Borg Helsinki Marathon 2026',
    shortName: 'Helsinki Marathon',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    time: '08:00',
    venueName: 'Olympiastadion',
    address: 'Paavo Nurmen tie 1',
    city: 'Helsinki',
    ticketUrl: 'https://www.helsinkimarathon.fi/',
    infoUrl: 'https://www.helsinkimarathon.fi/',
    image: null,
    categories: ['Urheilu', 'Juoksu', 'Marathon'],
    isFree: false,
    description: 'Helsingin suuri maratonpäivä — maraton, puolimaraton ja 10 km kaupungin halki.',
  },
  {
    id: 'designweek-2026',
    name: 'Helsinki Design Week 2026',
    shortName: 'Design Week',
    startDate: '2026-09-04',
    endDate: '2026-09-13',
    time: '10:00',
    venueName: 'Useita paikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://www.helsinkidesignweek.com/',
    infoUrl: 'https://www.helsinkidesignweek.com/',
    image: null,
    categories: ['Muotoilu', 'Kulttuuri', 'Festivaali', 'Taide'],
    isFree: false,
    description: 'Pohjoismaiden suurin muotoilufestivaali — 200+ tapahtumaa, näyttelyt, studiovisitit ja seminaarit ympäri Helsinkiä.',
  },
  {
    id: 'riff-2026',
    name: 'Rakkautta & Anarkiaa – Helsinki International Film Festival 2026',
    shortName: 'R&A HIFF',
    startDate: '2026-09-17',
    endDate: '2026-09-30',
    time: '12:00',
    venueName: 'Useita elokuvateattereita',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://hiff.fi/',
    infoUrl: 'https://hiff.fi/',
    image: null,
    categories: ['Elokuva', 'Festivaali', 'Kulttuuri'],
    isFree: false,
    description: 'Pohjoismaiden suurin elokuvafestivaali — 200+ elokuvaa, vierailevat ohjaajat ja maailmanensi-illat Helsingissä.',
  },
  {
    id: 'hcmf-2026',
    name: 'Helsinki Chamber Music Festival 2026',
    shortName: 'Helsinki Chamber Music Festival',
    startDate: '2026-07-02',
    endDate: '2026-07-05',
    time: '18:00',
    venueName: 'Useita tapahtumapaikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://www.helsinginkamarimusiikin.fi/',
    infoUrl: 'https://www.helsinginkamarimusiikin.fi/',
    image: null,
    categories: ['Klassinen', 'Musiikki', 'Festivaali', 'Kamarimusiikki'],
    isFree: false,
    description: 'Vuosittainen urbaani kamarimusiikin kesätapahtuma useissa Helsingin konserttisaleissa.',
  },
  {
    id: 'tikkurila-2026',
    name: 'Tikkurila Festivaali 2026',
    shortName: 'Tikkurila Festivaali',
    startDate: '2026-07-16',
    endDate: '2026-07-18',
    time: '12:00',
    venueName: 'Hiekkaharjun urheilupuisto',
    address: 'Hiekkaharju',
    city: 'Vantaa',
    ticketUrl: 'https://www.tikkurilafestivaali.fi/',
    infoUrl: 'https://www.tikkurilafestivaali.fi/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Pop', 'Rock'],
    isFree: false,
    description: 'Pääkaupunkiseudun suuri kesäfestivaali Vantaalla. Esiintyjinä mm. Eppu Normaali, Nylon Beat, KUUMAA, Egotrippi, The Rasmus.',
  },
  {
    id: 'lennykravitz-2026',
    name: 'Lenny Kravitz – Helsinki 2026',
    shortName: 'Lenny Kravitz',
    startDate: '2026-07-22',
    endDate: '2026-07-22',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Rock', 'Soul'],
    isFree: false,
    description: 'Nelinkertainen Grammy-palkittu Lenny Kravitz konsertoi Veikkaus Arenalla kesällä 2026.',
  },
  {
    id: 'pattismith-2026',
    name: 'Patti Smith – Helsinki 2026',
    shortName: 'Patti Smith',
    startDate: '2026-07-25',
    endDate: '2026-07-25',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Rock'],
    isFree: false,
    description: 'Rockmusiikin legenda ja vallankumouksellinen visionääri Patti Smith Veikkaus Arenalla.',
  },
  {
    id: 'jazzespa-2026',
    name: 'Jazz-Espa 2026',
    shortName: 'Jazz-Espa',
    startDate: '2026-07-27',
    endDate: '2026-08-01',
    time: '14:00',
    venueName: 'Espan lava',
    address: 'Esplanadi',
    city: 'Helsinki',
    ticketUrl: 'https://www.jazzespa.fi/',
    infoUrl: 'https://www.jazzespa.fi/',
    image: null,
    categories: ['Jazz', 'Musiikki', 'Ilmainen', 'Ulkoilma'],
    isFree: true,
    description: 'Ilmainen ulkoilmajazzfestivaali Espan lavalla — kotimaisia kokoonpanoja joka päivä.',
  },
  {
    id: 'scorpions-2026',
    name: 'Scorpions – Helsinki 2026',
    shortName: 'Scorpions',
    startDate: '2026-07-28',
    endDate: '2026-07-28',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Rock', 'Metal'],
    isFree: false,
    description: 'Legendaarinen saksalaisrokkyhtye Scorpions Veikkaus Arenalla kesäkiertueellaan.',
  },
  {
    id: 'hellsinki-metal-2026',
    name: 'Hellsinki Metal Festival 2026',
    shortName: 'Hellsinki Metal',
    startDate: '2026-08-07',
    endDate: '2026-08-08',
    time: '12:00',
    venueName: 'Helsinki',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://hellsinkifestival.com/',
    infoUrl: 'https://hellsinkifestival.com/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Metal'],
    isFree: false,
    description: 'Uusi metallifestivaali Helsingissä. Esiintyjinä mm. Opeth, Accept, Black Label Society, Triptykon, Bloodbath.',
  },
  {
    id: 'tapiola-2026',
    name: 'Tapiola Festivaali 2026',
    shortName: 'Tapiola Festivaali',
    startDate: '2026-08-14',
    endDate: '2026-08-15',
    time: '12:00',
    venueName: 'Tapiolan urheilupuisto',
    address: 'Tapiola',
    city: 'Espoo',
    ticketUrl: 'https://www.tapiolafestivaali.fi/',
    infoUrl: 'https://www.tapiolafestivaali.fi/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Pop', 'Rock'],
    isFree: false,
    description: 'Espoon Tapiolassa järjestettävä musiikkifestivaali lähes 50 artistilla.',
  },
  {
    id: 'viaporijazz-2026',
    name: 'Viapori Jazz 2026',
    shortName: 'Viapori Jazz',
    startDate: '2026-08-25',
    endDate: '2026-08-29',
    time: '12:00',
    venueName: 'Suomenlinna',
    address: 'Suomenlinna',
    city: 'Helsinki',
    ticketUrl: 'https://viaporijazz.fi/',
    infoUrl: 'https://viaporijazz.fi/',
    image: null,
    categories: ['Jazz', 'Musiikki', 'Festivaali', 'Ulkoilma'],
    isFree: false,
    description: 'Tuore musiikki soi wanhassa saaressa — Suomenlinna täyttyy kansainvälisestä jazzmusiikista.',
  },
  {
    id: 'earlymusic-2026',
    name: 'Helsinki Early Music Festival 2026',
    shortName: 'Early Music Festival',
    startDate: '2026-09-27',
    endDate: '2026-10-04',
    time: '18:00',
    venueName: 'Useita tapahtumapaikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://www.helsinkiearlymusic.fi/',
    infoUrl: 'https://www.helsinkiearlymusic.fi/',
    image: null,
    categories: ['Klassinen', 'Musiikki', 'Festivaali', 'Varhaismusiikki'],
    isFree: false,
    description: 'Varhaismusiikkiin keskittyvä festivaali — konsertteja historiallisissa tiloissa ympäri Helsinkiä.',
  },
  {
    id: 'placebo-2026',
    name: 'Placebo – Helsinki 2026',
    shortName: 'Placebo',
    startDate: '2026-10-18',
    endDate: '2026-10-18',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Rock', 'Alternative'],
    isFree: false,
    description: 'Vaihtoehtorockin suurtähti Placebo 30-vuotisjuhlakiertueellaan Veikkaus Arenalla.',
  },
  {
    id: 'joebonamassa-2026',
    name: 'Joe Bonamassa – Helsinki 2026',
    shortName: 'Joe Bonamassa',
    startDate: '2026-10-21',
    endDate: '2026-10-21',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Blues', 'Rock'],
    isFree: false,
    description: 'Maailman arvostetuin bluesrock-kitaristi Joe Bonamassa Veikkaus Arenalla.',
  },
  {
    id: 'etnosoi-2026',
    name: 'Etnosoi! 2026',
    shortName: 'Etnosoi!',
    startDate: '2026-10-30',
    endDate: '2026-11-08',
    time: '18:00',
    venueName: 'Useita tapahtumapaikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://www.etnosoi.fi/',
    infoUrl: 'https://www.etnosoi.fi/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Maailmanmusiikki', 'Kulttuuri'],
    isFree: false,
    description: 'Vuosittainen maailmanmusiikkifestivaali — konsertteja, klubi-iltoja ja oheistapahtumia ympäri Helsinkiä.',
  },
  {
    id: 'hellsinki-industrial-2026',
    name: 'Hellsinki Industrial Festival 2026',
    shortName: 'Hellsinki Industrial',
    startDate: '2026-11-19',
    endDate: '2026-11-21',
    time: '18:00',
    venueName: 'Ääniwalli',
    address: 'Helsinki',
    city: 'Helsinki',
    ticketUrl: 'https://hellsinkifestival.com/',
    infoUrl: 'https://hellsinkifestival.com/',
    image: null,
    categories: ['Musiikki', 'Festivaali', 'Elektroninen', 'Industrial', 'Dark'],
    isFree: false,
    description: 'Elektronisen musiikin klubifestivaali Ääniwallissa — dark-elektronista ja industrial-musiikkia.',
  },
  {
    id: 'nightvisions-2026',
    name: 'Night Visions 2026',
    shortName: 'Night Visions',
    startDate: '2026-11-25',
    endDate: '2026-11-29',
    time: '17:00',
    venueName: 'Useita elokuvateattereita',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://www.nightvisions.fi/',
    infoUrl: 'https://www.nightvisions.fi/',
    image: null,
    categories: ['Elokuva', 'Festivaali', 'Genre', 'Kauhu', 'Sci-fi'],
    isFree: false,
    description: 'Pohjoismaiden suurin genre-elokuvafestivaali — fantasia-, kauhu- ja sci-fi-elokuvia Helsingissä.',
  },
  {
    id: 'kuumaa-areena-2026',
    name: 'KUUMAA – Veikkaus Arena 2026',
    shortName: 'KUUMAA',
    startDate: '2026-11-28',
    endDate: '2026-11-28',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Pop'],
    isFree: false,
    description: 'Suomen suosituin yhtye KUUMAA juhlii 10-vuotista taivaltaan Veikkaus Arenalla.',
  },
  {
    id: 'pitbull-2026',
    name: 'Pitbull – Helsinki 2026',
    shortName: 'Pitbull',
    startDate: '2026-12-07',
    endDate: '2026-12-07',
    time: '19:00',
    venueName: 'Veikkaus Arena',
    address: 'Nordenskiöldinkatu 11-13',
    city: 'Helsinki',
    ticketUrl: 'https://www.livenation.fi/',
    infoUrl: 'https://www.veikkausareena.fi/',
    image: null,
    categories: ['Musiikki', 'Konsertti', 'Hip hop', 'Pop'],
    isFree: false,
    description: 'Rap-musiikin supertähti Pitbull Veikkaus Arenalla itsenäisyyspäivän jälkeen.',
  },
  {
    id: 'luxhelsinki-2027',
    name: 'Lux Helsinki 2027',
    shortName: 'Lux Helsinki',
    startDate: '2027-01-06',
    endDate: '2027-01-11',
    time: '17:00',
    venueName: 'Koko Helsinki',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://luxhelsinki.fi/',
    infoUrl: 'https://luxhelsinki.fi/',
    image: null,
    categories: ['Taide', 'Kulttuuri', 'Festivaali', 'Ilmainen', 'Ulkoilma'],
    isFree: true,
    description: 'Tutut rakennukset ja tilat muuntuvat ainutlaatuisiksi kaupunkitaideteoksiksi — ilmainen talvinen valofestaari.',
  },
  {
    id: 'balticcircle-2026',
    name: 'Baltic Circle 2026',
    shortName: 'Baltic Circle',
    startDate: '2026-11-12',
    endDate: '2026-11-15',
    time: '18:00',
    venueName: 'Useita paikkoja',
    address: '',
    city: 'Helsinki',
    ticketUrl: 'https://balticcircle.fi/',
    infoUrl: 'https://balticcircle.fi/',
    image: null,
    categories: ['Teatteri', 'Esittävä taide', 'Festivaali', 'Kulttuuri'],
    isFree: false,
    description: 'Kansainvälinen esittävän taiteen festivaali — kokeellista teatteria, tanssia ja performansseja Helsingissä.',
  },
]
