-- Siirrä kovakoodatut festivaalit Supabaseen
-- Aja tämä Supabase SQL -editorissa
-- Tyhjennä editori ensin, liitä koko sisältö, aja

INSERT INTO festivals (id, name, short_name, start_date, end_date, time, venue_name, address, city, ticket_url, info_url, image, categories, is_free, description, active)
VALUES
  ('hcf-2026', 'Helsinki City Festival 2026', 'Helsinki City Festival', '2026-06-12', '2026-06-14', '12:00', 'Nordis / Helsingin Jäähalli', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.helsinkicityfestival.fi/en/', 'https://www.helsinkicityfestival.fi/en/', NULL, ARRAY['Musiikki','Festivaali'], false, 'Kansainvälinen musiikkifestivaali Nordis-alueella. 50+ artistia kolmena päivänä.', true),
  ('tuska-2026', 'Tuska Open Air Metal Festival 2026', 'Tuska', '2026-06-26', '2026-06-28', '12:00', 'Suvilahti', 'Koksikatu 4', 'Helsinki', 'https://tuska.fi/en/tickets/', 'https://tuska.fi/en/', NULL, ARRAY['Musiikki','Festivaali','Metal'], false, 'Pohjoismaiden suurin metallifestivaali Suvilahden entisellä voimalaitosalueella.', true),
  ('jytakesa-2026', 'Jytäkesä Go-Go 2026', 'Jytäkesä Go-Go', '2026-07-31', '2026-08-01', '12:00', 'Suvilahti', 'Koksikatu 4', 'Helsinki', 'https://www.tiketti.fi/jytakesa-go-go-2026-suvilahti-helsinki-lippuja/110812', 'https://jytakesagogo.com', 'https://jytakesagogo.com/wp-content/uploads/2025/11/jytis26_header.jpg', ARRAY['Musiikki','Festivaali','Rock'], false, 'Kahden päivän rock- ja indie-musiikkifestivaali Suvilahden kentällä. Esiintyjinä mm. Turbonegro, Risto, Ismo Alanko, Fun Lovin'' Criminals.', true),
  ('flow-2026', 'Flow Festival 2026', 'Flow Festival', '2026-08-14', '2026-08-16', '12:00', 'Suvilahti', 'Koksikatu 4', 'Helsinki', 'https://www.flowfestival.com/en/tickets/', 'https://www.flowfestival.com/en/', NULL, ARRAY['Musiikki','Festivaali'], false, 'Premium musiikki- ja taidefestivaali Suvilahden teollisuusalueella. 90 000 kävijää kolmena päivänä.', true),
  ('juhlaviikot-2026', 'Helsingin juhlaviikot 2026', 'Juhlaviikot', '2026-08-18', '2026-09-05', '10:00', 'Useita paikkoja', '', 'Helsinki', 'https://helsinkifestival.fi/en/', 'https://helsinkifestival.fi/en/', NULL, ARRAY['Kulttuuri','Festivaali','Taide','Musiikki'], false, 'Helsingin suurin kulttuurifestivaali — konsertit, teatteri, tanssi ja taide ympäri kaupunkia.', true),
  ('taiteidentyo-2026', 'Taiteiden yö 2026', 'Taiteiden yö', '2026-08-20', '2026-08-20', '18:00', 'Koko Helsinki', '', 'Helsinki', 'https://helsinkifestival.fi/taiteidenyo/en/', 'https://helsinkifestival.fi/taiteidenyo/en/', NULL, ARRAY['Kulttuuri','Taide','Ilmainen'], true, 'Yöllinen taidetapahtuma — museot, galleriat, teatterit ja kaupunkitila avautuvat ilmaiseksi yöhön asti.', true),
  ('suuretoluet-2026', 'Suuret Oluet – Pienet Panimot Helsinki 2026', 'Suuret Oluet Helsinki', '2026-07-12', '2026-07-27', '12:00', 'Rautatientori', 'Rautatientori', 'Helsinki', 'https://www.tiketti.fi/', 'https://suuretoluet.fi/helsinki/', NULL, ARRAY['Olut','Ruoka & juoma','Festivaali','Ulkoilma'], false, 'Suomen suurin craft beer -tapahtuma Rautatientorilla. 50+ pientä panimoa, 200+ olutta.', true),
  ('kallioblockparty-2026', 'Kallio Block Party 2026', 'Kallio Block Party', '2026-08-01', '2026-08-01', '12:00', 'Kallio, Helsinki', 'Fleminginkatu / Helsinginkatu', 'Helsinki', 'https://www.kallioblockparty.org/', 'https://www.kallioblockparty.org/', NULL, ARRAY['Musiikki','Festivaali','Ilmainen','Ulkoilma'], true, 'Kallion vuotuinen ilmainen katufestivaali — live-musiikkia, ruokaa ja yhteisöllisyyttä koko päivä.', true),
  ('wejazz-2026', 'We Jazz Festival 2026', 'We Jazz', '2026-11-19', '2026-11-22', '18:00', 'Useita paikkoja', '', 'Helsinki', 'https://wejazz.fi/', 'https://wejazz.fi/', NULL, ARRAY['Jazz','Musiikki','Festivaali'], false, 'Helsingin kansainvälinen jazzfestivaali — esiintymispaikkoja ympäri kaupunkia.', true),
  ('slush-2026', 'Slush 2026', 'Slush', '2026-11-18', '2026-11-19', '09:00', 'Messukeskus', 'Messuaukio 1', 'Helsinki', 'https://slush.org/', 'https://slush.org/', NULL, ARRAY['Teknologia','Startup','Verkostoituminen'], false, 'Maailman johtava startup- ja teknologiatapahtuma. 13 000+ kävijää Messukeskuksessa.', true),
  ('pride-2026', 'Helsinki Pride 2026', 'Helsinki Pride', '2026-06-27', '2026-07-04', '10:00', 'Esplanadi / Kauppatori', 'Esplanadi', 'Helsinki', 'https://www.helsinkipride.fi/', 'https://www.helsinkipride.fi/', NULL, ARRAY['Pride','Kulttuuri','Festivaali','Ilmainen'], true, 'Suomen suurin Pride-viikko — paraati, tapahtumat ja juhla LGBTQ+-yhteisölle ja kaikille.', true),
  ('tasteofhelsinki-2026', 'Taste of Helsinki 2026', 'Taste of Helsinki', '2026-06-04', '2026-06-07', '12:00', 'Kansalaistori', 'Kansalaistori 1', 'Helsinki', 'https://www.tasteofhelsinki.fi/', 'https://www.tasteofhelsinki.fi/', NULL, ARRAY['Ruoka & juoma','Festivaali','Ravintola'], false, 'Helsingin parhaiden ravintoloiden pop-up festivaali Kansalaistorilla — huippukeittiöt, ruokamestariat ja juomatarjoilu.', true),
  ('marathon-2026', 'Björn Borg Helsinki Marathon 2026', 'Helsinki Marathon', '2026-08-22', '2026-08-23', '08:00', 'Olympiastadion', 'Paavo Nurmen tie 1', 'Helsinki', 'https://www.helsinkimarathon.fi/', 'https://www.helsinkimarathon.fi/', NULL, ARRAY['Urheilu','Juoksu','Marathon'], false, 'Helsingin suuri maratonpäivä — maraton, puolimaraton ja 10 km kaupungin halki.', true),
  ('designweek-2026', 'Helsinki Design Week 2026', 'Design Week', '2026-09-04', '2026-09-13', '10:00', 'Useita paikkoja', '', 'Helsinki', 'https://www.helsinkidesignweek.com/', 'https://www.helsinkidesignweek.com/', NULL, ARRAY['Muotoilu','Kulttuuri','Festivaali','Taide'], false, 'Pohjoismaiden suurin muotoilufestivaali — 200+ tapahtumaa, näyttelyt, studiovisitit ja seminaarit ympäri Helsinkiä.', true),
  ('riff-2026', 'Rakkautta & Anarkiaa – Helsinki International Film Festival 2026', 'R&A HIFF', '2026-09-17', '2026-09-30', '12:00', 'Useita elokuvateattereita', '', 'Helsinki', 'https://hiff.fi/', 'https://hiff.fi/', NULL, ARRAY['Elokuva','Festivaali','Kulttuuri'], false, 'Pohjoismaiden suurin elokuvafestivaali — 200+ elokuvaa, vierailevat ohjaajat ja maailmanensi-illat Helsingissä.', true),
  ('hcmf-2026', 'Helsinki Chamber Music Festival 2026', 'Helsinki Chamber Music Festival', '2026-07-02', '2026-07-05', '18:00', 'Useita tapahtumapaikkoja', '', 'Helsinki', 'https://www.helsinginkamarimusiikin.fi/', 'https://www.helsinginkamarimusiikin.fi/', NULL, ARRAY['Klassinen','Musiikki','Festivaali','Kamarimusiikki'], false, 'Vuosittainen urbaani kamarimusiikin kesätapahtuma useissa Helsingin konserttisaleissa.', true),
  ('tikkurila-2026', 'Tikkurila Festivaali 2026', 'Tikkurila Festivaali', '2026-07-16', '2026-07-18', '12:00', 'Hiekkaharjun urheilupuisto', 'Hiekkaharju', 'Vantaa', 'https://www.tikkurilafestivaali.fi/', 'https://www.tikkurilafestivaali.fi/', NULL, ARRAY['Musiikki','Festivaali','Pop','Rock'], false, 'Pääkaupunkiseudun suuri kesäfestivaali Vantaalla. Esiintyjinä mm. Eppu Normaali, Nylon Beat, KUUMAA, Egotrippi, The Rasmus.', true),
  ('lennykravitz-2026', 'Lenny Kravitz – Helsinki 2026', 'Lenny Kravitz', '2026-07-22', '2026-07-22', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Rock','Soul'], false, 'Nelinkertainen Grammy-palkittu Lenny Kravitz konsertoi Veikkaus Arenalla kesällä 2026.', true),
  ('pattismith-2026', 'Patti Smith – Helsinki 2026', 'Patti Smith', '2026-07-25', '2026-07-25', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Rock'], false, 'Rockmusiikin legenda ja vallankumouksellinen visionääri Patti Smith Veikkaus Arenalla.', true),
  ('jazzespa-2026', 'Jazz-Espa 2026', 'Jazz-Espa', '2026-07-27', '2026-08-01', '14:00', 'Espan lava', 'Esplanadi', 'Helsinki', 'https://www.jazzespa.fi/', 'https://www.jazzespa.fi/', NULL, ARRAY['Jazz','Musiikki','Ilmainen','Ulkoilma'], true, 'Ilmainen ulkoilmajazzfestivaali Espan lavalla — kotimaisia kokoonpanoja joka päivä.', true),
  ('scorpions-2026', 'Scorpions – Helsinki 2026', 'Scorpions', '2026-07-28', '2026-07-28', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Rock','Metal'], false, 'Legendaarinen saksalaisrokkyhtye Scorpions Veikkaus Arenalla kesäkiertueellaan.', true),
  ('hellsinki-metal-2026', 'Hellsinki Metal Festival 2026', 'Hellsinki Metal', '2026-08-07', '2026-08-08', '12:00', 'Helsinki', '', 'Helsinki', 'https://hellsinkifestival.com/', 'https://hellsinkifestival.com/', NULL, ARRAY['Musiikki','Festivaali','Metal'], false, 'Uusi metallifestivaali Helsingissä. Esiintyjinä mm. Opeth, Accept, Black Label Society, Triptykon, Bloodbath.', true),
  ('tapiola-2026', 'Tapiola Festivaali 2026', 'Tapiola Festivaali', '2026-08-14', '2026-08-15', '12:00', 'Tapiolan urheilupuisto', 'Tapiola', 'Espoo', 'https://www.tapiolafestivaali.fi/', 'https://www.tapiolafestivaali.fi/', NULL, ARRAY['Musiikki','Festivaali','Pop','Rock'], false, 'Espoon Tapiolassa järjestettävä musiikkifestivaali lähes 50 artistilla.', true),
  ('viaporijazz-2026', 'Viapori Jazz 2026', 'Viapori Jazz', '2026-08-25', '2026-08-29', '12:00', 'Suomenlinna', 'Suomenlinna', 'Helsinki', 'https://viaporijazz.fi/', 'https://viaporijazz.fi/', NULL, ARRAY['Jazz','Musiikki','Festivaali','Ulkoilma'], false, 'Tuore musiikki soi wanhassa saaressa — Suomenlinna täyttyy kansainvälisestä jazzmusiikista.', true),
  ('earlymusic-2026', 'Helsinki Early Music Festival 2026', 'Early Music Festival', '2026-09-27', '2026-10-04', '18:00', 'Useita tapahtumapaikkoja', '', 'Helsinki', 'https://www.helsinkiearlymusic.fi/', 'https://www.helsinkiearlymusic.fi/', NULL, ARRAY['Klassinen','Musiikki','Festivaali','Varhaismusiikki'], false, 'Varhaismusiikkiin keskittyvä festivaali — konsertteja historiallisissa tiloissa ympäri Helsinkiä.', true),
  ('placebo-2026', 'Placebo – Helsinki 2026', 'Placebo', '2026-10-18', '2026-10-18', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Rock','Alternative'], false, 'Vaihtoehtorockin suurtähti Placebo 30-vuotisjuhlakiertueellaan Veikkaus Arenalla.', true),
  ('joebonamassa-2026', 'Joe Bonamassa – Helsinki 2026', 'Joe Bonamassa', '2026-10-21', '2026-10-21', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Blues','Rock'], false, 'Maailman arvostetuin bluesrock-kitaristi Joe Bonamassa Veikkaus Arenalla.', true),
  ('etnosoi-2026', 'Etnosoi! 2026', 'Etnosoi!', '2026-10-30', '2026-11-08', '18:00', 'Useita tapahtumapaikkoja', '', 'Helsinki', 'https://www.etnosoi.fi/', 'https://www.etnosoi.fi/', NULL, ARRAY['Musiikki','Festivaali','Maailmanmusiikki','Kulttuuri'], false, 'Vuosittainen maaillanmusiikkifestivaali — konsertteja, klubi-iltoja ja oheistapahtumia ympäri Helsinkiä.', true),
  ('hellsinki-industrial-2026', 'Hellsinki Industrial Festival 2026', 'Hellsinki Industrial', '2026-11-19', '2026-11-21', '18:00', 'Ääniwalli', 'Helsinki', 'Helsinki', 'https://hellsinkifestival.com/', 'https://hellsinkifestival.com/', NULL, ARRAY['Musiikki','Festivaali','Elektroninen','Industrial','Dark'], false, 'Elektronisen musiikin klubifestivaali Ääniwallissa — dark-elektronista ja industrial-musiikkia.', true),
  ('nightvisions-2026', 'Night Visions 2026', 'Night Visions', '2026-11-25', '2026-11-29', '17:00', 'Useita elokuvateattereita', '', 'Helsinki', 'https://www.nightvisions.fi/', 'https://www.nightvisions.fi/', NULL, ARRAY['Elokuva','Festivaali','Genre','Kauhu','Sci-fi'], false, 'Pohjoismaiden suurin genre-elokuvafestivaali — fantasia-, kauhu- ja sci-fi-elokuvia Helsingissä.', true),
  ('kuumaa-areena-2026', 'KUUMAA – Veikkaus Arena 2026', 'KUUMAA', '2026-11-28', '2026-11-28', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Pop'], false, 'Suomen suosituin yhtye KUUMAA juhlii 10-vuotista taivaltaan Veikkaus Arenalla.', true),
  ('pitbull-2026', 'Pitbull – Helsinki 2026', 'Pitbull', '2026-12-07', '2026-12-07', '19:00', 'Veikkaus Arena', 'Nordenskiöldinkatu 11-13', 'Helsinki', 'https://www.livenation.fi/', 'https://www.veikkausareena.fi/', NULL, ARRAY['Musiikki','Konsertti','Hip hop','Pop'], false, 'Rap-musiikin supertähti Pitbull Veikkaus Arenalla itsenäisyyspäivän jälkeen.', true),
  ('luxhelsinki-2027', 'Lux Helsinki 2027', 'Lux Helsinki', '2027-01-06', '2027-01-11', '17:00', 'Koko Helsinki', '', 'Helsinki', 'https://luxhelsinki.fi/', 'https://luxhelsinki.fi/', NULL, ARRAY['Taide','Kulttuuri','Festivaali','Ilmainen','Ulkoilma'], true, 'Tutut rakennukset ja tilat muuntuvat ainutlaatuisiksi kaupunkitaideteoksiksi — ilmainen talvinen valofestaari.', true),
  ('balticcircle-2026', 'Baltic Circle 2026', 'Baltic Circle', '2026-11-12', '2026-11-15', '18:00', 'Useita paikkoja', '', 'Helsinki', 'https://balticcircle.fi/', 'https://balticcircle.fi/', NULL, ARRAY['Teatteri','Esittävä taide','Festivaali','Kulttuuri'], false, 'Kansainvälinen esittävän taiteen festivaali — kokeellista teatteria, tanssia ja performansseja Helsingissä.', true)
ON CONFLICT (id) DO NOTHING;

-- Tarkista tulos
SELECT id, name, start_date FROM festivals ORDER BY start_date;
